version: '3'

services:
    fappstore:
        container_name: fappstore
        image: 'postgres:12'
        ports:
            - '5432:5432'
        environment:
            POSTGRES_DB: 'fappdb_loc'
            POSTGRES_USER: 'fappdb_user'
            POSTGRES_PASSWORD: 'fappdb_password'
        volumes:
            - ./db/data:/var/lib/postgresql/data

    fappserver:
        container_name: fappserver
        image: 'qrivi/fappserver:latest'
        restart: always
        ports:
            - '8080:8080'
        depends_on:
            - fappstore
