version: '3'

services:
  fappstore:
    container_name: fappstore
    image: 'mongo:4.2.2'
    ports:
      - '27017:27017'
    command: 'mongod'

  fappserver:
    container_name: fappserver
    image: 'qrivi/fappserver:latest'
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - fappstore