name: CI - build & test

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Java 14
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 14

      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Lint Project
        run: ./gradlew ktlintCheck

      - name: Build Project
        run: ./gradlew build
