name: CI - deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Java 14
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 14

      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: ./gradlew clean build jibDockerBuild

      - name: Push Docker Image
        run: |
          docker push qrivi/nuntium-server
